/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const Cart = IDL.Record({
  'totalRupees' : IDL.Nat,
  'items' : IDL.Vec(CartItem),
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'dispatched' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'debitCreditCard' : IDL.Null,
  'netBanking' : IDL.Null,
});
export const DeliveryDetails = IDL.Record({
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'priceRupees' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'totalRupees' : IDL.Nat,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'deliveryDetails' : DeliveryDetails,
  'createdAt' : Timestamp,
  'items' : IDL.Vec(OrderItem),
});
export const ProductSpec = IDL.Record({
  'value' : IDL.Text,
  'specLabel' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'priceRupees' : IDL.Nat,
  'specs' : IDL.Vec(ProductSpec),
  'weightKg' : IDL.Nat,
});
export const InquiryId = IDL.Nat;

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [Cart], []),
  'clearCart' : IDL.Func([], [], []),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'placeOrder' : IDL.Func([DeliveryDetails, PaymentMethod], [OrderId], []),
  'removeFromCart' : IDL.Func([ProductId], [Cart], []),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [InquiryId],
      [],
    ),
  'updateCartItem' : IDL.Func([ProductId, IDL.Nat], [Cart], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const Cart = IDL.Record({
    'totalRupees' : IDL.Nat,
    'items' : IDL.Vec(CartItem),
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'dispatched' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'debitCreditCard' : IDL.Null,
    'netBanking' : IDL.Null,
  });
  const DeliveryDetails = IDL.Record({
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'priceRupees' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'totalRupees' : IDL.Nat,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'deliveryDetails' : DeliveryDetails,
    'createdAt' : Timestamp,
    'items' : IDL.Vec(OrderItem),
  });
  const ProductSpec = IDL.Record({
    'value' : IDL.Text,
    'specLabel' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'priceRupees' : IDL.Nat,
    'specs' : IDL.Vec(ProductSpec),
    'weightKg' : IDL.Nat,
  });
  const InquiryId = IDL.Nat;
  
  return IDL.Service({
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [Cart], []),
    'clearCart' : IDL.Func([], [], []),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'placeOrder' : IDL.Func([DeliveryDetails, PaymentMethod], [OrderId], []),
    'removeFromCart' : IDL.Func([ProductId], [Cart], []),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [InquiryId],
        [],
      ),
    'updateCartItem' : IDL.Func([ProductId, IDL.Nat], [Cart], []),
  });
};

export const init = ({ IDL }) => { return []; };