/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'totalRupees' : bigint, 'items' : Array<CartItem> }
export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export interface DeliveryDetails {
  'city' : string,
  'fullName' : string,
  'address' : string,
  'phone' : string,
  'pincode' : string,
}
export type InquiryId = bigint;
export interface Order {
  'id' : OrderId,
  'totalRupees' : bigint,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'deliveryDetails' : DeliveryDetails,
  'createdAt' : Timestamp,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'productId' : ProductId,
  'priceRupees' : bigint,
  'quantity' : bigint,
}
export type OrderStatus = { 'pending' : null } |
  { 'dispatched' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type PaymentMethod = { 'upi' : null } |
  { 'debitCreditCard' : null } |
  { 'netBanking' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'priceRupees' : bigint,
  'specs' : Array<ProductSpec>,
  'weightKg' : bigint,
}
export type ProductId = bigint;
export interface ProductSpec { 'value' : string, 'specLabel' : string }
export type Timestamp = bigint;
export interface _SERVICE {
  'addToCart' : ActorMethod<[ProductId, bigint], Cart>,
  'clearCart' : ActorMethod<[], undefined>,
  'getCart' : ActorMethod<[], Cart>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'placeOrder' : ActorMethod<[DeliveryDetails, PaymentMethod], OrderId>,
  'removeFromCart' : ActorMethod<[ProductId], Cart>,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, string],
    InquiryId
  >,
  'updateCartItem' : ActorMethod<[ProductId, bigint], Cart>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];